Gallery.create!([
  { user_id: 1, name: "Alli" },
  { user_id: 1, name: "Emma - Shailene Woodley" },
  { user_id: 1, name: "Emma - Shailene Woodley (Short Hair)" },
  { user_id: 1, name: "Jenny" },
  { user_id: 2, name: "bellfounding" },
  { user_id: 2, name: "floofcoaster" },
  { user_id: 2, name: "her_imperial_radiance" },
  { user_id: 2, name: "inourhead" },
  { user_id: 2, name: "isthisart" },
  { user_id: 2, name: "lexicality" },
  { user_id: 2, name: "liakoura" },
  { user_id: 2, name: "luminous_regnant" },
  { user_id: 2, name: "mind_game" },
  { user_id: 2, name: "pandion" },
  { user_id: 2, name: "salt_of_the" },
  { user_id: 2, name: "self_composed" },
  { user_id: 2, name: "thaumobabble" },
  { user_id: 3, name: "bitofafiction" },
  { user_id: 3, name: "calendarofcrime" },
  { user_id: 3, name: "edgeofyourseat" },
  { user_id: 3, name: "gloriousdawn" },
  { user_id: 3, name: "manofmyword" },
  { user_id: 3, name: "poeticterms" },
  { user_id: 3, name: "thevictorious" },
  { user_id: 3, name: "thisvorlunatic" },
  { user_id: 3, name: "unmarred" },
  { user_id: 3, name: "unmired" },
  { user_id: 3, name: "unmirrored" },
])

puts "Assigning galleries to characters..."
CharactersGallery.create!([
  { character_id: 5, gallery_id: 2 },
  { character_id: 4, gallery_id: 2, section_order: 0 },
  { character_id: 4, gallery_id: 3, section_order: 1 },
  { character_id: 7, gallery_id: 4 },
  { character_id: 3, gallery_id: 1 },
  { character_id: 6, gallery_id: 4 },
  { character_id: 2, gallery_id: 1 },
  { character_id: 25, gallery_id: 1 },
  { character_id: 29, gallery_id: 5 },
  { character_id: 17, gallery_id: 6 },
  { character_id: 10, gallery_id: 7 },
  { character_id: 12, gallery_id: 8 },
  { character_id: 28, gallery_id: 9 },
  { character_id: 15, gallery_id: 10 },
  { character_id: 14, gallery_id: 11 },
  { character_id: 30, gallery_id: 12 },
  { character_id: 13, gallery_id: 13 },
  { character_id: 16, gallery_id: 14 },
  { character_id: 18, gallery_id: 15 },
  { character_id: 31, gallery_id: 16 },
  { character_id: 32, gallery_id: 17 },
  { character_id: 20, gallery_id: 18 },
  { character_id: 11, gallery_id: 19 },
  { character_id: 19, gallery_id: 20 },
  { character_id: 21, gallery_id: 21 },
  { character_id: 22, gallery_id: 23 },
  { character_id: 24, gallery_id: 24 },
  { character_id: 27, gallery_id: 25 },
  { character_id: 33, gallery_id: 22 },
  { character_id: 26, gallery_id: 26, section_order: 0, added_by_group: true },
  { character_id: 26, gallery_id: 27, section_order: 1, added_by_group: true },
  { character_id: 26, gallery_id: 28, section_order: 2, added_by_group: true },
])

puts "Populating galleries with icons..."
GalleriesIcon.create!([
  { icon_id: 101, gallery_id: 1 },
  { icon_id: 5, gallery_id: 1 },
  { icon_id: 6, gallery_id: 2 },
  { icon_id: 7, gallery_id: 3 },
  { icon_id: 8, gallery_id: 3 },
  { icon_id: 10, gallery_id: 4 },
  { icon_id: 13, gallery_id: 5 },
  { icon_id: 14, gallery_id: 5 },
  { icon_id: 15, gallery_id: 6 },
  { icon_id: 16, gallery_id: 6 },
  { icon_id: 17, gallery_id: 7 },
  { icon_id: 18, gallery_id: 8 },
  { icon_id: 19, gallery_id: 8 },
  { icon_id: 20, gallery_id: 9 },
  { icon_id: 21, gallery_id: 9 },
  { icon_id: 22, gallery_id: 9 },
  { icon_id: 23, gallery_id: 9 },
  { icon_id: 24, gallery_id: 9 },
  { icon_id: 25, gallery_id: 10 },
  { icon_id: 26, gallery_id: 10 },
  { icon_id: 27, gallery_id: 11 },
  { icon_id: 28, gallery_id: 11 },
  { icon_id: 29, gallery_id: 12 },
  { icon_id: 30, gallery_id: 12 },
  { icon_id: 31, gallery_id: 13 },
  { icon_id: 32, gallery_id: 13 },
  { icon_id: 33, gallery_id: 13 },
  { icon_id: 34, gallery_id: 13 },
  { icon_id: 35, gallery_id: 13 },
  { icon_id: 36, gallery_id: 14 },
  { icon_id: 37, gallery_id: 14 },
  { icon_id: 38, gallery_id: 14 },
  { icon_id: 39, gallery_id: 15 },
  { icon_id: 40, gallery_id: 15 },
  { icon_id: 41, gallery_id: 16 },
  { icon_id: 42, gallery_id: 16 },
  { icon_id: 43, gallery_id: 17 },
  { icon_id: 44, gallery_id: 17 },
  { icon_id: 45, gallery_id: 17 },
  { icon_id: 46, gallery_id: 17 },
  { icon_id: 47, gallery_id: 18 },
  { icon_id: 48, gallery_id: 18 },
  { icon_id: 49, gallery_id: 19 },
  { icon_id: 50, gallery_id: 19 },
  { icon_id: 51, gallery_id: 19 },
  { icon_id: 52, gallery_id: 19 },
  { icon_id: 53, gallery_id: 19 },
  { icon_id: 54, gallery_id: 19 },
  { icon_id: 55, gallery_id: 19 },
  { icon_id: 56, gallery_id: 19 },
  { icon_id: 57, gallery_id: 19 },
  { icon_id: 58, gallery_id: 19 },
  { icon_id: 59, gallery_id: 19 },
  { icon_id: 60, gallery_id: 19 },
  { icon_id: 61, gallery_id: 19 },
  { icon_id: 62, gallery_id: 19 },
  { icon_id: 63, gallery_id: 19 },
  { icon_id: 64, gallery_id: 20 },
  { icon_id: 65, gallery_id: 20 },
  { icon_id: 66, gallery_id: 21 },
  { icon_id: 67, gallery_id: 21 },
  { icon_id: 68, gallery_id: 21 },
  { icon_id: 69, gallery_id: 21 },
  { icon_id: 70, gallery_id: 21 },
  { icon_id: 71, gallery_id: 22 },
  { icon_id: 72, gallery_id: 22 },
  { icon_id: 73, gallery_id: 22 },
  { icon_id: 74, gallery_id: 23 },
  { icon_id: 75, gallery_id: 23 },
  { icon_id: 76, gallery_id: 23 },
  { icon_id: 77, gallery_id: 23 },
  { icon_id: 78, gallery_id: 23 },
  { icon_id: 79, gallery_id: 23 },
  { icon_id: 80, gallery_id: 23 },
  { icon_id: 81, gallery_id: 23 },
  { icon_id: 82, gallery_id: 23 },
  { icon_id: 83, gallery_id: 23 },
  { icon_id: 84, gallery_id: 23 },
  { icon_id: 85, gallery_id: 24 },
  { icon_id: 86, gallery_id: 24 },
  { icon_id: 87, gallery_id: 24 },
  { icon_id: 88, gallery_id: 25 },
  { icon_id: 89, gallery_id: 25 },
  { icon_id: 90, gallery_id: 26 },
  { icon_id: 91, gallery_id: 26 },
  { icon_id: 92, gallery_id: 26 },
  { icon_id: 93, gallery_id: 27 },
  { icon_id: 94, gallery_id: 27 },
  { icon_id: 95, gallery_id: 28 },
  { icon_id: 96, gallery_id: 28 },
  { icon_id: 97, gallery_id: 1 },
  { icon_id: 100, gallery_id: 2 },
  { icon_id: 98, gallery_id: 4 },
])
