Post.create!([
  {
    board_id: 3,
    user_id: 5,
    subject: "sample thread",
    content: "",
    editor_mode: "html",
    icon_id: 4,
    created_at: "2018-11-27 02:25:52",
    updated_at: "2018-12-06 00:05:13",
    status: 0,
    section_order: 0,
    edited_at: "2018-11-27 02:25:52",
    tagged_at: "2018-12-06 00:05:13",
    authors_locked: true,
    unjoined_author_ids: [1],
  },
  {
    board_id: 3,
    user_id: 6,
    subject: "html test",
    content: "test content",
    editor_mode: "html",
    icon_id: 5,
    created_at: "2019-06-22 03:38:40",
    updated_at: "2019-06-22 03:38:40",
    status: 0,
    section_order: 1,
    edited_at: "2019-06-22 03:38:40",
    tagged_at: "2019-06-22 03:38:40",
    description: "test description",
    authors_locked: false,
  },
  {
    board_id: 1,
    user_id: 3,
    subject: "(adventures in effulgence)",
    content: "He has been in Forks, Washington for six months and they have been the most excruciatingly boring six months of his life to date.<br><br>There are so many things he can't do here, because this town is so <em>small</em>, and if anything gets back to Daddy dearest they'll just move somewhere <em>worse</em>. He honestly can't imagine anywhere worse, but then, before Forks he couldn't have imagined Forks.<br><br>Getting in fights at school is one of the few remaining forms of entertainment he can find any joy in, and it's also necessary for a few other reasons. So he doesn't waste any time on his first day back: it's ten after ten, he just got out of Art, the hallways are full of students rushing from class to class, and he finds one of the boys who already hates him a little and gives him a hard shove into the corner of a row of lockers.<br><br>Success. The crowd tries to stream around them at first, but at the point where the other boy has him on the ground and is punching him repeatedly in the face, traffic has come to a halt on all sides.",
    editor_mode: "html",
    character_id: 19,
    icon_id: 65,
    created_at: "2012-09-13 00:56:00",
    updated_at: "2012-09-13 02:00:00",
    status: 1,
    section_id: 1,
    section_order: 0,
    edited_at: "2012-09-13 00:56:00",
    tagged_at: "2012-09-13 02:00:00",
    authors_locked: true,
    unjoined_author_ids: [2],
  },
  {
    board_id: 1,
    user_id: 2,
    subject: "one enormous bruise",
    content: "Bella arrives to gym early, having gotten directions to it well in advance - over lunch with a helpful Jessica.  Jessica is helpful in many ways, and is also able to provide what might well be an exhaustive list of people Delaney has goaded, what sports teams they are on, and how hunky each one is in Jessica's personal estimation.  \"The teachers never see any of it,\" she said.  \"And they'd assume Delaney was getting bullied, anyway, wouldn't they?  But you saw.  Something's wrong with him, but it's only the things he <em>does</em> that get him hurt.\"<br><br>Bella has a note from her old gym teacher, who let her exhaust herself on an exercise bike in the back instead of doing something hazardous any time the classroom activity would have otherwise placed Bella near a ball or another human being.  Bella also has the copay receipts from all of her doctor's visits over the past year, and has written on each one what sent her to the clinic, ranging from two instances of \"had to check for concussion\" to one of \"chipped molar\" to one of \"two broken toes, also carpet rash\".  And just because of gym teachers' reputation for not being interested in excuses, she has thrown in drugstore receipts too, each with massive purchases of disinfectants, bandaids, and other first aid items suitable in quantity for only an extremely accident-prone individual.  Bella has these things because Renée is not really equipped to reliably run basic errands before they become emergencies, and Bella's had a checking account to handle such things since she was not quite fifteen.<br><br>She finds the gym, and looks around for the teacher.",
    editor_mode: "html",
    character_id: 31,
    created_at: "2012-09-13 14:47:00",
    updated_at: "2012-09-13 20:32:00",
    status: 1,
    section_id: 1,
    section_order: 1,
    edited_at: "2012-09-13 14:47:00",
    tagged_at: "2012-09-13 20:32:00",
    authors_locked: true,
    unjoined_author_ids: [3],
  },
  {
    board_id: 1,
    user_id: 2,
    subject: "but you like an audience",
    content: "Bella arrives early to her next gym class, too. Delaney's not there yet, which is annoying, because he knows how to solve a puzzle.<br><br>Charlie knows a few things about Delaney and his family.  The most interesting thing is this: Delaney appeared in the hospital with broken ribs, once.  He did not do this crowing about how much fun it was to be stomped on/thrown down the stairs/whatever.  He did this with no explanation at all.  Charlie doesn't need victim cooperation to press charges for battery - but he does need someone to press charges against.<br><br>And no one at school saw a thing.<br><br>Audiences, indeed.",
    editor_mode: "html",
    character_id: 31,
    icon_id: 42,
    created_at: "2012-09-13 17:50:00",
    updated_at: "2012-09-13 22:06:00",
    status: 1,
    section_id: 1,
    section_order: 2,
    edited_at: "2012-09-13 17:50:00",
    tagged_at: "2012-09-13 22:06:00",
    authors_locked: true,
    unjoined_author_ids: [3],
  },
  {
    board_id: 1,
    user_id: 3,
    subject: "you have the means in your possession",
    content: "Lunch has just started and there are not very many people in the cafeteria, but apparently there isn't enough room for these two students to stand in line next to one another without... friction.<br><br>It begins with a scowl. Well, a scowl from the taller of the two. Delaney honestly doesn't seem to care. Unfortunately, this is not the correct response.",
    editor_mode: "html",
    character_id: 19,
    created_at: "2012-09-13 22:14:00",
    updated_at: "2012-09-13 23:20:00",
    status: 1,
    section_id: 1,
    section_order: 3,
    edited_at: "2012-09-13 22:14:00",
    tagged_at: "2012-09-13 23:20:00",
    authors_locked: true,
    unjoined_author_ids: [2],
  },
  {
    board_id: 1,
    user_id: 2,
    subject: "i drive better than i walk",
    content: "Bella leaves school that afternoon not having had any notable conversation with Delaney before or after gym.  She's just making a beeline for the blue station wagon her dad found her, cheap and functional if not very loveable.  She's got homework to pick through and an email to Renée to write.  She might go to a movie with Jessica later.",
    editor_mode: "html",
    character_id: 31,
    icon_id: 42,
    created_at: "2012-09-13 20:22:00",
    updated_at: "2012-09-14 00:10:00",
    status: 1,
    section_id: 1,
    section_order: 4,
    edited_at: "2012-09-13 20:22:00",
    tagged_at: "2012-09-14 00:10:00",
    authors_locked: true,
    unjoined_author_ids: [3],
  },
  {
    board_id: 1,
    user_id: 2,
    subject: "it's not that there's nothing to do, it's that all of those things are boring",
    content: "Bella rolls over onto her back.  She's been doing leg lifts.  Now her legs hurt.  She's going to lie there for a while, and then she's going to drive home, and then she's going to write about a paragraph of Government essay before expiring from boredom.  Jessica is sick.  Angela is babysitting.  They're still doing stuff she's covered in Bio and books she's read in English; it would take better teachers than she has to make Spanish and Trig interesting.  A trip to Port Angeles to <em>do</em> something is the work of an entire day, not a school afternoon.  She really needs to save up and buy more books.  Or take up - quilting, or something.<br><br>Sigh.",
    editor_mode: "html",
    character_id: 31,
    created_at: "2012-09-13 21:12:00",
    updated_at: "2012-09-15 22:24:00",
    status: 1,
    section_id: 1,
    section_order: 5,
    edited_at: "2012-09-13 21:12:00",
    tagged_at: "2012-09-15 22:24:00",
    authors_locked: true,
    unjoined_author_ids: [3],
  },
  {
    board_id: 1,
    user_id: 2,
    subject: "if you eat the food of the dead, you can never leave hades, so i guess that wasn't hades",
    content: "Bella still brings her lunch most of the time.  Today, she is chipping away at the leftovers of the pasta monstrosity her father made when left to fend for himself.  She has not yet had a chance to talk up Hilary's cooking because it would have seemed cruel in the aftermath of the... meal.<br><br>It's actually pretty edible after she added all that garlic and butter.<br><br>Jessica sits with her, and Angela, and then Mike; Eric's with some other friends today.  There's an empty chair to her left; Angela's on her right, and the other two face them.",
    editor_mode: "html",
    character_id: 31,
    icon_id: 42,
    created_at: "2012-09-15 19:29:00",
    updated_at: "2012-09-16 00:32:00",
    status: 1,
    section_id: 1,
    section_order: 6,
    edited_at: "2012-09-15 19:29:00",
    tagged_at: "2012-09-16 00:32:00",
    authors_locked: true,
    unjoined_author_ids: [3],
  },
  {
    board_id: 1,
    user_id: 2,
    subject: "why would you even bother telling someone your secrets before killing them",
    content: "By the end of Bio, the halls are full of people eager to inform Bella and everyone else within earshot that her friend is a murderer.  They have entirely the wrong attitude to have formed the impression because he just now murdered someone, and also her father hasn't come looking for her yet, so this is probably nonsense.<br><br>Bella goes to gym.",
    editor_mode: "html",
    character_id: 31,
    icon_id: 42,
    created_at: "2012-09-15 21:37:00",
    updated_at: "2012-09-17 18:09:00",
    status: 1,
    section_id: 1,
    section_order: 7,
    edited_at: "2012-09-15 21:37:00",
    tagged_at: "2012-09-17 18:09:00",
    authors_locked: true,
    unjoined_author_ids: [3],
  },
  {
    board_id: 1,
    user_id: 2,
    subject: "if i got three wishes, first i'd find out all about how wishes work",
    content: "Bella brings two blank notebooks to school the next day.  Her old one is safely computerized and boxed up with its predecessors.<br><br>At lunch, she sits with Angela; Jessica and Eric and Lauren sit at the same table but mostly talk to each other, and Mike is nowhere to be seen.<br><br>Bella is just about on time to gym, thanks to an overnight icing that means she has to pick her way with extreme care across the slippery grass or the slick sidewalks.  The second time she falls down, she gives up on attempting any dignity at all, and, cradling her thwacked elbow, scoots the rest of the way to the gym on her rear.  This leaves her with damp jeans but no further injuries, and they were a little damp anyway from the falls.<br><br>She doesn't have time to do more than smile and wave at Alice on her way to get her mat and get out of the way of careening balls.  She spends the class doing the subset of her safe activities that won't stress her elbow.",
    editor_mode: "html",
    character_id: 31,
    created_at: "2012-09-17 15:24:00",
    updated_at: "2012-09-20 03:14:00",
    status: 1,
    section_id: 1,
    section_order: 8,
    edited_at: "2012-09-17 15:24:00",
    tagged_at: "2012-09-20 03:14:00",
    authors_locked: true,
    unjoined_author_ids: [3],
  },
  {
    board_id: 1,
    user_id: 2,
    subject: "we will seek my buried inheritance",
    content: "Bella fixes French toast for breakfast to salvage stale bread, and, having seen Charlie off to work, hops in her own car and makes for Alice's house.  She arrives at nine-thirty, and goes up to the doorbell and rings it.",
    editor_mode: "html",
    character_id: 31,
    icon_id: 42,
    created_at: "2012-09-20 13:01:00",
    updated_at: "2012-09-21 17:46:00",
    status: 1,
    section_id: 1,
    section_order: 9,
    edited_at: "2012-09-20 13:01:00",
    tagged_at: "2012-09-21 17:46:00",
    authors_locked: true,
    unjoined_author_ids: [3],
  },
  {
    board_id: 1,
    user_id: 2,
    subject: "unconsciousness would be an undesirable outcome",
    content: "On Sunday, Bella drives to the movie theater with Angela in tow, and her car breaks on the way home from Angela's house.  She calls a tow truck, and calls her dad, and she goes home in the cop car and her station wagon goes on vacation to the mechanic.<br><br>On Monday, Charlie drives Bella to school.<br><br>As she's been discharged from the car and Charlie pulls away, a van driven by a panicking teenager screams out of nowhere towards Bella.<br><br>Making wishes is easy.<br><br>It is not automatic.  It is not instantaneous.<br><br>The van creams Bella, good and proper.",
    editor_mode: "html",
    character_id: 31,
    created_at: "2012-09-21 15:18:00",
    updated_at: "2012-09-23 18:01:00",
    status: 1,
    section_id: 2,
    section_order: 0,
    edited_at: "2012-09-21 15:18:00",
    tagged_at: "2012-09-23 18:01:00",
    authors_locked: true,
    unjoined_author_ids: [3],
  },
  {
    board_id: 1,
    user_id: 2,
    subject: "i believe i can fly",
    content: "Alice eventually goes home for the evening.<br><br>Bella goes up and sits in her room.<br><br>She has five hexes.<br><br><em>Five</em>.<br><br>That's rather a lot of hexes.<br><br>She gets out her notebook, with the lists, and she makes some wishes.<br><br>And then she goes to bed, grinning.<br><br>In the morning it will be time to make plans.",
    editor_mode: "html",
    character_id: 31,
    created_at: "2012-09-23 15:04:00",
    updated_at: "2012-09-25 22:34:00",
    status: 1,
    section_id: 2,
    section_order: 1,
    edited_at: "2012-09-23 15:04:00",
    tagged_at: "2012-09-25 22:34:00",
    authors_locked: true,
    unjoined_author_ids: [3],
  },
  {
    board_id: 1,
    user_id: 2,
    subject: "I will take over the world in the tiniest of pieces",
    content: "Bella thinks and thinks and thinks.  It takes some getting used to not to have to write everything down in order for it to be where she left it when she wants it again.  [You going to school today?] she asks Alice, when the time he arrived yesterday has been and gone.<br><br>Because that would make some of the thinking she has to do easier, and some of it trickier.",
    editor_mode: "html",
    character_id: 31,
    icon_id: 42,
    created_at: "2012-09-25 20:03:00",
    updated_at: "2012-09-27 17:34:00",
    status: 1,
    section_id: 2,
    section_order: 2,
    edited_at: "2012-09-25 20:03:00",
    tagged_at: "2012-09-27 17:34:00",
    authors_locked: true,
    unjoined_author_ids: [3],
  },
  {
    board_id: 1,
    user_id: 2,
    subject: "you have the right to remain silent, but no one else will be using theirs",
    content: "Delaney Hammond, Sr., does not know that he is going to be arrested.  It is not hard to find his flight, learn that the chauffeur can also fly the tiny family airplane and will be bringing the boss directly to Forks's little airport to save transit time, and be there to meet them at the airport with a pair of uniforms.<br><br>So Charlie does all that.<br><br>\"Delaney Hammond, you are under arrest,\" Charlie says, while Joshua puts on cuffs and Terry makes sure the chauffeur isn't going to interfere.  \"You have the right to remain silent...\" The Miranda rights just pour out, like they're all one word; Charlie doesn't really think about them.  He doesn't even skip the part about how this ridiculously rich person could be provided a public defender if he cannot afford one.",
    editor_mode: "html",
    character_id: 31,
    icon_id: 42,
    created_at: "2012-09-27 14:40:00",
    updated_at: "2012-09-28 18:09:00",
    status: 1,
    section_id: 2,
    section_order: 3,
    edited_at: "2012-09-27 14:40:00",
    tagged_at: "2012-09-28 18:09:00",
    authors_locked: true,
    unjoined_author_ids: [3],
  },
  {
    board_id: 1,
    user_id: 2,
    subject: "technically not karma",
    content: "Paul S. Washington, defense attorney, is having the <em>worst</em> day.<br><br>He got the case referred to him by a New York firm that sometimes deals with his when they need to work on interests that involve or take place in Washington State.  This qualifies - dad knocks around his kid a little, kid gets fed up even though he could have moved out months ago if he'd get off his ass and find a job instead of complaining, dad is offering a very nice hourly rate.  So far so good.<br><br>His coffee maker breaks.  He has instant instead, but burns his hand when he drinks it.  A car alarm within earshot seems to be going off every six minutes.  <em>His</em> car starts fine, and then strands him in the middle of the highway.  His cell dies halfway through the call to AAA, and he sits there waiting for them to find him based on which highway he's on without any further details.  Eventually they do, he borrows the driver's cell to call a cab, the cab takes an hour to get there, the cabbie gets lost and still charges him for the full distance driven, and finally he's at the police station in Forks - a little nowhere town - to talk to his client, but not before he trips gracelessly over the threshold and nearly breaks his nose.<br><br>Ugh.<br><br>It had <em>better</em> be a very nice hourly rate.",
    editor_mode: "html",
    character_id: 31,
    icon_id: 42,
    created_at: "2012-09-28 15:19:00",
    updated_at: "2012-09-28 20:46:00",
    status: 1,
    section_id: 2,
    section_order: 4,
    edited_at: "2012-09-28 15:19:00",
    tagged_at: "2012-09-28 20:46:00",
    authors_locked: true,
    unjoined_author_ids: [3],
  },
  {
    board_id: 1,
    user_id: 2,
    subject: "be as you aren't to make them feel as they ought",
    content: "Lucinda Daly, prosecutor, wants to talk to her plaintiff.  He's a little hard to find, but a few phone calls get her on the phone with Charlie, who suggests that Laney might be at his house, as he's friends with his daughter.  Lucinda offers to come by when Charlie's home, but Charlie says she can go over now if she likes; a friend of the family she might want to talk to anyway is an adult presence there.<br><br>Lucinda pulls into the driveway and rings the doorbell.",
    editor_mode: "html",
    character_id: 31,
    icon_id: 42,
    created_at: "2012-09-28 17:52:00",
    updated_at: "2012-09-29 00:19:00",
    status: 1,
    section_id: 2,
    section_order: 5,
    edited_at: "2012-09-28 17:52:00",
    tagged_at: "2012-09-29 00:19:00",
    authors_locked: true,
    unjoined_author_ids: [3],
  },
  {
    board_id: 1,
    user_id: 2,
    subject: "all rise",
    content: "No plea bargain is struck.  The jury is picked, and Lucinda asks a few random ones whether they have accepted bribes and sees who looks nervous: no one, as it turns out, so she strikes people who are too young to have children and one fellow who looks like he hates the entire world for her picks.  Paul strikes a grandmotherly type and someone who admits when asked that they don't think much of rich people.<br><br>\"All rise,\" comes the command as Judge Roberts walks in.",
    editor_mode: "html",
    character_id: 31,
    icon_id: 43,
    created_at: "2012-09-28 21:29:00",
    updated_at: "2012-09-30 17:24:00",
    status: 1,
    section_id: 2,
    section_order: 6,
    edited_at: "2012-09-28 21:29:00",
    tagged_at: "2012-09-30 17:24:00",
    authors_locked: true,
    unjoined_author_ids: [3],
  },
  {
    board_id: 1,
    user_id: 2,
    subject: "we're kind of inexplicable",
    content: "Bella's return - she's decided that no one knows a damn thing about how quickly fractures of unknown severity can heal, so she's not limping anymore, and wears only a mostly-symbolic handful of (actual) bandaids in some visible locations - is the talk of the school.  Mike even talks to her again, solicitously demanding (annoying), wanting the story, wanting to be the first to know if she needs anything, wanting to walk her to class in case she falls; she's cool to him, but not outright cold, she doesn't want <em>enemies</em> if she doesn't have to make them.  Tyler Crowley, van driver, apologizes so profusely that she expects him to offer her his life in servitude.  Jessica cases Bella quickly and efficiently for any details of the story that weren't obvious (Bella hit by van, injured, out of school two weeks, back with only minor scratches left) and then serves as a very convenient buffer for everyone else.  Eric wants to know if Bella has scars.  Lauren wants to know if Bella's car is fixed yet.  Angela doesn't like the attention <em>she's</em> getting for having been Bella's schoolwork-ferry for the duration.<br><br>Bella wants to eat her damn lunch.  Sigh.",
    editor_mode: "html",
    character_id: 31,
    icon_id: 42,
    created_at: "2012-09-30 14:38:00",
    updated_at: "2012-10-01 00:17:00",
    status: 1,
    section_id: 2,
    section_order: 7,
    edited_at: "2012-09-30 14:38:00",
    tagged_at: "2012-10-01 00:17:00",
    authors_locked: true,
    unjoined_author_ids: [3],
  },
  {
    board_id: 1,
    user_id: 2,
    subject: "now isn't that something",
    content: "Everyone's found out about Alice's dad the next day.  \"You know your friend Delaney?  His dad is in <em>jail!</em>!\" is the first thing Jessica says at lunch.<br><br>\"Criminal tendencies run in the family, I guess,\" Mike says darkly.<br><br>\"Mike, be nice,\" pouts Jessica.  \"It was for abuse!\"<br><br>\"Doesn't that run in families too,\" Lauren says; it's not really a question.  \"Bella, I dunno if you're sleeping with him yet, but don't have his kids, right?\"<br><br>\"Bella's not sleeping with Hammond!\" exclaims Mike stridently.  This exclamation is not less annoying for being true.<br><br>\"You're not, right?\" Eric asks Bella.  She rolls her eyes and shakes her head.<br><br>\"Grow <em>manners</em>,\" says Jessica.  It's not clear to whom.<br><br>\"Grow <em>eyes</em>,\" snorts Lauren.  \"Delaney wants to bang her worse than you do, Mike, and I read the paper too and now he's got millions of dollars.\"<br><br>\"I do not - I haven't - you're -\" sputters Mike.<br><br>Bella has no idea why these people still sit with her.  All she did was plunk down next to Angela and Angela's new boyfriend Ben.  She remains stoically silent.",
    editor_mode: "html",
    character_id: 31,
    created_at: "2012-09-30 21:27:00",
    updated_at: "2012-10-01 19:40:00",
    status: 1,
    section_id: 2,
    section_order: 8,
    edited_at: "2012-09-30 21:27:00",
    tagged_at: "2012-10-01 19:40:00",
    authors_locked: true,
    unjoined_author_ids: [3],
  },
  {
    board_id: 1,
    user_id: 2,
    subject: "welcome to wonderland",
    content: "Mike doesn't try to sit with Bella anymore.  She only had to get up and walk away twice.  Now he sits with some other friends in another corner of the cafeteria and doesn't bother her.  She can sit with Angela and Angela's boyfriend and Jessica and Jessica's current boyfriend and sometimes Eric and sometimes Lauren.<br><br>\"So,\" Jessica says.  \"Bella, did you know Delaney came to school <em>in a dress</em>?\"<br><br>\"Oh?\" Bella says.  \"I wonder if he made it himself.\"<br><br>Jessica looks rather stunned that Bella could miss the point by so wide a margin.<br><br>[You came to school in a dress, huh?] Bella inquires.",
    editor_mode: "html",
    character_id: 31,
    icon_id: 43,
    created_at: "2012-10-01 17:07:00",
    updated_at: "2012-10-01 22:58:00",
    status: 1,
    section_id: 2,
    section_order: 9,
    edited_at: "2012-10-01 17:07:00",
    tagged_at: "2012-10-01 22:58:00",
    authors_locked: true,
    unjoined_author_ids: [3],
  },
  {
    board_id: 1,
    user_id: 2,
    subject: "some people are this impressive without magic, but how?",
    content: "It has been six weeks since Bella sent out her applications and it is now the end of March.  She has been on the soccer team since that time, winning the one game they've had against the team from the Quileute reservation, and has introduced Charlie to her flute (he's nonplussed but proud), and has been keeping straight A's in everything.<br><br>She has received four rejections (Harvard, Yale, MIT, and Princeton).  The other schools are still quiet on the subject of applicant Bella Swan.  Except Stanford.<br><br>Stanford thinks she is interesting, and would like to interview her in person, when would be convenient for her?<br><br>Hmm.<br><br>[Hey Alice.  If anybody asks you, would you mind telling them you bought me a motorcycle?]<br><br>She can drive herself to the airport.",
    editor_mode: "html",
    character_id: 31,
    icon_id: 42,
    created_at: "2012-10-01 20:08:00",
    updated_at: "2012-10-02 02:00:00",
    status: 1,
    section_id: 2,
    section_order: 10,
    edited_at: "2012-10-01 20:08:00",
    tagged_at: "2012-10-02 02:00:00",
    authors_locked: true,
    unjoined_author_ids: [3],
  },
  {
    board_id: 1,
    user_id: 2,
    subject: "here goes",
    content: "Bella schedules an appointment at Stanford.  She breezes through sixteen hours of motorcycle class, mostly by demonstrating that the instructor is redundant and wouldn't he rather teach her exotic motorcycle tricks and then just mark her as passing the course?  She plays in a soccer game against a Port Angeles high school and wins.  She starts driving her bike to school, and she names it Tegu after a lizard of similar coloring, because it needed a name.<br><br>On Friday evening she's due to fly out, crash in a Stanford grad student's house overnight, interview on Saturday, and fly home that evening.  She bikes for the airport, black leather gold-studded saddlebags over Tegu's back wheel carrying her luggage.",
    editor_mode: "html",
    character_id: 31,
    icon_id: 42,
    created_at: "2012-10-01 23:09:00",
    updated_at: "2012-10-03 22:16:00",
    status: 1,
    section_id: 2,
    section_order: 11,
    edited_at: "2012-10-01 23:09:00",
    tagged_at: "2012-10-03 22:16:00",
    authors_locked: true,
    unjoined_author_ids: [3],
  },
  {
    board_id: 1,
    user_id: 2,
    subject: "who are you when you're alone?",
    content: "A week later, Bella receives a fancy acceptance letter from Stanford.  Squee!<br><br>[I'm in,] she tells Alice merrily.",
    editor_mode: "html",
    character_id: 31,
    icon_id: 42,
    created_at: "2012-10-03 19:37:00",
    updated_at: "2012-10-04 00:14:00",
    status: 1,
    section_id: 2,
    section_order: 12,
    edited_at: "2012-10-03 19:37:00",
    tagged_at: "2012-10-04 00:14:00",
    authors_locked: true,
    unjoined_author_ids: [3],
  },
  {
    board_id: 1,
    user_id: 2,
    subject: "high school is kind of boring really",
    content: "School plods along.  Bella is native-quality fluent in Spanish, professor-level at math, well and thoroughly versed in the workings of the United States government, capable of doing actual independent research projects in biology, and she's been speaking English since she was <em>one</em>.  Alas, these skills only make classes easier for a short time.  After the novelty wears off they're just tedious.  Bella winds up squaring her homework done more often than not so she can work out the kinks in her design for telekinesis, or play music, or attend soccer practice, or write little computer games, or read, or just fly around.  This works out fine.  Magic is pretty good at homework.<br><br>She winds up not attending most of the dances, but she does want to go to the end of year one, as she will be leaving Forks High School forever and it has some good points.  Alice promised her a dress...",
    editor_mode: "html",
    character_id: 31,
    icon_id: 43,
    created_at: "2012-10-03 22:36:00",
    updated_at: "2012-10-08 09:49:00",
    status: 1,
    section_id: 3,
    section_order: 0,
    edited_at: "2012-10-03 22:36:00",
    tagged_at: "2012-10-08 09:49:00",
    authors_locked: true,
    unjoined_author_ids: [3],
  },
  {
    board_id: 1,
    user_id: 2,
    subject: "good morning",
    content: "The next morning, Charlie leaves late for work so he and Bella can have breakfast together, but then he does go.<br><br>Bella sees him off.<br><br>And heads for the lair, humming, all nerves.",
    editor_mode: "html",
    character_id: 31,
    created_at: "2012-10-08 15:31:00",
    updated_at: "2012-10-09 15:24:00",
    status: 1,
    section_id: 3,
    section_order: 1,
    edited_at: "2012-10-08 15:31:00",
    tagged_at: "2012-10-09 15:24:00",
    authors_locked: true,
    unjoined_author_ids: [3],
  },
  {
    board_id: 1,
    user_id: 2,
    subject: "introduction to being a college student",
    content: "Bella packs light.  (She can conjure whatever she wants, mooch off Alice for anything she wants to <em>buy</em>.  She's wearing her riding gear and riding Tegu and only has a few other favorite-things she'd like to retain in their original forms.  The black dress is one of them.)  Her swag goes in saddlebags and she goes to Stanford.<br><br>It's a road trip; she wants to be able to account for her time, and besides, she likes her motorcycle.  She checks into crappy little motels and once spends four minutes watching someone try and fail to disassemble her bike, from her window.  (The fellow gives up eventually.  Tegu does not want to come apart or move.)<br><br>At Stanford, she is there before her new roommate, who is reportedly named \"Janine\".  Bella unpacks, and since no one's there yet, she wishes up some decorations too.  She introduces herself to the RA, Maureen, and then loiters in the hall lounge, waiting for more people to meet.",
    editor_mode: "html",
    character_id: 31,
    created_at: "2012-10-09 12:27:00",
    updated_at: "2012-10-11 00:27:00",
    status: 1,
    section_id: 3,
    section_order: 2,
    edited_at: "2012-10-09 12:27:00",
    tagged_at: "2012-10-11 00:27:00",
    authors_locked: true,
    unjoined_author_ids: [3],
  },
  {
    board_id: 1,
    user_id: 2,
    subject: "dress for success",
    content: "By the time when Alice first shows up at Stanford <em>visibly</em> (as opposed to lurking around the ceiling at Bella's classes, making smart remarks in her head), Janine has put in a request, and so have four other girls on the hall.  (Lillian wants a summery floral dress, Tasha wants a midnight blue evening gown, Ruth has expressed a fondness for polka dots, and Kuo wants something gothy.  Bella politely makes no remarks about <em>anyone's</em> taste.)<br><br>Bella likes all her teachers okay, and also the orchestra conductor and her soccer coach.  Life is good.",
    editor_mode: "html",
    character_id: 31,
    icon_id: 42,
    created_at: "2012-10-10 21:38:00",
    updated_at: "2012-10-11 18:49:00",
    status: 1,
    section_id: 3,
    section_order: 3,
    edited_at: "2012-10-10 21:38:00",
    tagged_at: "2012-10-11 18:49:00",
    authors_locked: true,
    unjoined_author_ids: [3],
  },
  {
    board_id: 1,
    user_id: 2,
    subject: "interesting rich people",
    content: "The party guest list includes a wide range of interestingnesses of rich people.  There's a fellow who sits on various boards of various faceless corporations; there's two who started startups and swept up a few million dollars that way; there's a small handful of professional philanthropists, who have oodles of money from various sources and make a hobby of distributing the interest to worthy pet causes; there is a congresswoman, and a state senator, both from New York but apparently willing to travel to the West Coast on occasion.  There's also a lot of dull old money who do this sort of thing and nothing but all the time, but they still concentrate a lot of financial leverage, and Bella would rather have ins with them than <em>not</em>, as long as she can.<br><br>She bikes up - speeding shamefully, hexing herself radar detection, and cutting the trip in half from its estimated time to just eight hours on the road.  Tegu can go <em>very very fast</em>.<br><br>Alice made her a new dress for the occasion - this one's autumny, mostly a dark red-brown, with leaf patterns in deep gold and burnt orange swirling up around and soft ruffles in the same colors around her knees and puffing out over one shoulder.  It stands out more than the little black dress - which is fine.  She would like attention, and just being the hostess's son's girlfriend will not quite get her there at a rich people party, she thinks.",
    editor_mode: "html",
    character_id: 31,
    icon_id: 42,
    created_at: "2012-10-11 17:19:00",
    updated_at: "2012-10-12 19:02:00",
    status: 1,
    section_id: 3,
    section_order: 4,
    edited_at: "2012-10-11 17:19:00",
    tagged_at: "2012-10-12 19:02:00",
    authors_locked: true,
    unjoined_author_ids: [3],
  },
  {
    board_id: 1,
    user_id: 2,
    subject: "for my birthday i become a real person",
    content: "The eighteenth birthday is the best one.  Bella is no longer A Minor.  She no longer needs Charlie's or Renée's permission to do random things that real people are allowed to do.  She still can't drink, but she doesn't feel like throwing her cognitive edge out a window anyway.<br><br>Also, she is going to get a cake.",
    editor_mode: "html",
    character_id: 31,
    icon_id: 42,
    created_at: "2012-10-12 16:02:00",
    updated_at: "2012-10-12 21:18:00",
    status: 1,
    section_id: 3,
    section_order: 5,
    edited_at: "2012-10-12 16:02:00",
    tagged_at: "2012-10-12 21:18:00",
    authors_locked: true,
    unjoined_author_ids: [3],
  },
  {
    board_id: 1,
    user_id: 2,
    subject: "style substance subterfuge",
    content: "Miles-toting is a reasonably fun part of Elli's job.  She is privy to such secrets as \"where he is being toted from\" and \"who he will be when picked up to be toted\",
    so she's the one who fetches Miles Vorkosigan, watches over his transformation into Miles Naismith, and accompanies the latter to his destination, pretending this time to be business partners (she Sales And Marketing, he eccentrically Development, product Top Secret).<br><br>Currently they're sliding back into their ranks and uniforms - she's got her Dendarii pants on already and lovely scarlet accessories to turn them into shiny silver fashion statements.  But before they fully reintegrate with their outfit and she dons the rest of <em>her</em> outfit there is a hospital visit to make.<br><br>The survivors of the incident, such as they are, aren't in great shape.  Miles knows how the dead-and-irrecoverable wanted to be disposed of; he knows his obligations to the crippled, likewise, and he discharges them with all the gravity and generosity that could be wished.  Quinn wants his job, so she watches him do it, even this least lovely part.  Reminds her a little of the news that her face was getting artistically replaced.  But that doesn't mean she doesn't wonder why he has to get that up close and personal with Aziz, who after all probably can't understand a word he says.<br><br>Miles demurs with something about a fascinated fear of the loss of mind, and Elli lets it go.<br><br>They get good news about Marilac, about the value of their work there.<br><br>They split up so that he can shower, and she can get into her greys, and then there's going to be the usual meeting.",
    editor_mode: "html",
    created_at: "2015-07-22 17:44:00",
    updated_at: "2019-06-22 18:40:31",
    status: :abandoned,
    section_order: 0,
    edited_at: "2019-06-22 18:40:31",
    tagged_at: "2015-07-23 00:59:00",
    authors_locked: true,
    unjoined_author_ids: [3],
  },
  {
    board_id: 5,
    user_id: 3,
    subject: "unread post",
    content: "<p>sample text</p>",
    editor_mode: "rtf",
    character_id: 23,
    icon_id: 3,
    created_at: "2018-08-18 21:19:27",
    updated_at: "2018-08-18 21:22:43",
    status: 0,
    section_order: 0,
    edited_at: "2018-08-18 21:19:27",
    tagged_at: "2018-08-18 21:22:43",
    authors_locked: true,
    unjoined_author_ids: [4],
  },
])

puts "Setting up post views..."
Post::View.create!([
  { post_id: 1, user_id: 5, read_at: "2018-12-06 00:05:13" },
  { post_id: 1, user_id: 1, read_at: "2018-12-06 00:05:13" },
  { post_id: 1, user_id: 3, read_at: "2019-05-06 23:07:00" },
  { post_id: 2, user_id: 3, read_at: "2019-06-22 07:40:11" },
  { post_id: 4, user_id: 3 },
  { post_id: 7, user_id: 3, ignored: true },
  { post_id: 3, user_id: 3, read_at: "2019-06-06 01:53:29" },
  { post_id: 32, user_id: 3, read_at: "2015-07-23 00:57:00" },
  { post_id: 33, user_id: 3, read_at: "2019-08-18 21:22:42" },
])
