# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `aws-actionmailer-ses` gem.
# Please instead update this file by running `bin/tapioca gem aws-actionmailer-ses`.


# source://aws-actionmailer-ses//lib/aws/action_mailer/ses/mailer.rb#5
module Aws; end

# source://aws-actionmailer-ses//lib/aws/action_mailer/ses/mailer.rb#6
module Aws::ActionMailer; end

# @api private
#
# source://aws-actionmailer-ses//lib/aws/action_mailer/railtie.rb#6
class Aws::ActionMailer::Railtie < ::Rails::Railtie; end

# source://aws-actionmailer-ses//lib/aws/action_mailer/ses/mailer.rb#7
module Aws::ActionMailer::SES; end

# Provides a delivery method for ActionMailer that uses Amazon Simple Email Service.
#
# Delivery settings are used to construct a new Aws::SES::Client instance.
# Once you have a delivery method, you can configure your Rails environment to use it:
#
#     config.action_mailer.delivery_method = :ses
#     config.action_mailer.ses_settings = { region: 'us-west-2' }
#
# @see https://guides.rubyonrails.org/action_mailer_basics.html
#
# source://aws-actionmailer-ses//lib/aws/action_mailer/ses/mailer.rb#17
class Aws::ActionMailer::SES::Mailer
  # @param settings [Hash] Passes along initialization options to
  #   [Aws::SES::Client.new](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/SES/Client.html#initialize-instance_method).
  # @return [Mailer] a new instance of Mailer
  #
  # source://aws-actionmailer-ses//lib/aws/action_mailer/ses/mailer.rb#22
  def initialize(settings = T.unsafe(nil)); end

  # Delivers a Mail::Message object. Called during mail delivery.
  #
  # source://aws-actionmailer-ses//lib/aws/action_mailer/ses/mailer.rb#29
  def deliver!(message); end

  # Returns the value of attribute settings.
  #
  # source://aws-actionmailer-ses//lib/aws/action_mailer/ses/mailer.rb#18
  def settings; end
end

# source://aws-actionmailer-ses//lib/aws-actionmailer-ses.rb#10
Aws::ActionMailer::SES::VERSION = T.let(T.unsafe(nil), String)

# source://aws-actionmailer-ses//lib/aws/action_mailer/ses_v2/mailer.rb#7
module Aws::ActionMailer::SESV2; end

# Provides a delivery method for ActionMailer that uses Amazon Simple Email Service V2.
#
# Delivery settings are used to construct a new Aws::SESV2::Client instance.
# Once you have a delivery method, you can configure your Rails environment to use it:
#
#     config.action_mailer.delivery_method = :ses_v2
#     config.action_mailer.ses_v2_settings = { region: 'us-west-2' }
#
# @see https://guides.rubyonrails.org/action_mailer_basics.html
#
# source://aws-actionmailer-ses//lib/aws/action_mailer/ses_v2/mailer.rb#17
class Aws::ActionMailer::SESV2::Mailer
  # @param settings [Hash] Passes along initialization settings to
  #   [Aws::SESV2::Client.new](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/SESV2/Client.html#initialize-instance_method).
  # @return [Mailer] a new instance of Mailer
  #
  # source://aws-actionmailer-ses//lib/aws/action_mailer/ses_v2/mailer.rb#22
  def initialize(settings = T.unsafe(nil)); end

  # Delivers a Mail::Message object. Called during mail delivery.
  #
  # source://aws-actionmailer-ses//lib/aws/action_mailer/ses_v2/mailer.rb#29
  def deliver!(message); end

  # Returns the value of attribute settings.
  #
  # source://aws-actionmailer-ses//lib/aws/action_mailer/ses_v2/mailer.rb#18
  def settings; end

  private

  # smtp_envelope_from will default to the From address *without* sender names.
  # By omitting this param, SESv2 will correctly use sender names from the mail headers.
  # We should only use smtp_envelope_from when it was explicitly set (instance variable set)
  #
  # source://aws-actionmailer-ses//lib/aws/action_mailer/ses_v2/mailer.rb#48
  def from_email_address(message); end

  # smtp_envelope_to will default to the full destinations (To, Cc, Bcc)
  # SES v2 API prefers each component split out into a destination hash.
  # When smtp_envelope_to was set, use it explicitly for to_address only.
  #
  # source://aws-actionmailer-ses//lib/aws/action_mailer/ses_v2/mailer.rb#55
  def to_addresses(message); end
end

# source://aws-actionmailer-ses//lib/aws-actionmailer-ses.rb#14
Aws::ActionMailer::SESV2::VERSION = T.let(T.unsafe(nil), String)
