# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `haml-rails` gem.
# Please instead update this file by running `bin/tapioca gem haml-rails`.


# source://haml-rails//lib/haml-rails.rb#7
module Haml; end

# source://haml-rails//lib/haml-rails.rb#8
module Haml::Rails; end

# source://haml-rails//lib/haml-rails.rb#9
class Haml::Rails::Railtie < ::Rails::Railtie; end
