# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `redis-namespace` gem.
# Please instead update this file by running `bin/tapioca gem redis-namespace`.


# source://redis-namespace//lib/redis/namespace/version.rb#3
class Redis
  include ::Redis::Commands::Bitmaps
  include ::Redis::Commands::Cluster
  include ::Redis::Commands::Connection
  include ::Redis::Commands::Geo
  include ::Redis::Commands::Hashes
  include ::Redis::Commands::HyperLogLog
  include ::Redis::Commands::Keys
  include ::Redis::Commands::Lists
  include ::Redis::Commands::Pubsub
  include ::Redis::Commands::Scripting
  include ::Redis::Commands::Server
  include ::Redis::Commands::Sets
  include ::Redis::Commands::SortedSets
  include ::Redis::Commands::Streams
  include ::Redis::Commands::Strings
  include ::Redis::Commands::Transactions
end

# source://redis-namespace//lib/redis/namespace/version.rb#4
class Redis::Namespace
  # @return [Namespace] a new instance of Namespace
  #
  # source://redis-namespace//lib/redis/namespace.rb#260
  def initialize(namespace, options = T.unsafe(nil)); end

  # source://redis-namespace//lib/redis/namespace.rb#286
  def _client; end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def append(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def auth(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#374
  def bgrewriteaof(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#374
  def bgsave(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def bitcount(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def bitop(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def bitpos(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def blpop(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def brpop(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def brpoplpush(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def bzpopmax(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def bzpopmin(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#441
  def call_with_namespace(command, *args, **_arg2, &block); end

  # This operation can run for a very long time if the namespace contains lots of keys!
  # It should be used in tests, or when the namespace is small enough
  # and you are sure you know what you are doing.
  #
  # source://redis-namespace//lib/redis/namespace.rb#350
  def clear; end

  # source://redis-namespace//lib/redis/namespace.rb#280
  def client; end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def close(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#374
  def config(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#334
  def connection; end

  # source://redis-namespace//lib/redis/namespace.rb#374
  def dbsize(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def debug(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def decr(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def decrby(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def del(*args, **_arg1, &block); end

  # @return [Boolean]
  #
  # source://redis-namespace//lib/redis/namespace.rb#272
  def deprecations?; end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def discard(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def disconnect!(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def dump(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def echo(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#342
  def eval(*args, **_arg1); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def evalsha(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#338
  def exec; end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def exists(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def exists?(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def expire(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def expireat(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def expiretime(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#374
  def flushall(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#374
  def flushdb(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#330
  def full_namespace; end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def get(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def getbit(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def getex(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def getrange(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def getset(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def hdel(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def hexists(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def hget(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def hgetall(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def hincrby(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def hincrbyfloat(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def hkeys(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def hlen(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def hmget(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def hmset(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def hscan(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def hscan_each(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def hset(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def hsetnx(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def hvals(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def incr(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def incrby(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def incrbyfloat(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#374
  def info(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#423
  def inspect; end

  # source://redis-namespace//lib/redis/namespace.rb#305
  def keys(query = T.unsafe(nil)); end

  # source://redis-namespace//lib/redis/namespace.rb#374
  def lastsave(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def lindex(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def linsert(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def llen(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def lpop(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def lpush(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def lpushx(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def lrange(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def lrem(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def lset(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def ltrim(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def mapped_hmget(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def mapped_hmset(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def mapped_mget(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def mapped_mset(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def mapped_msetnx(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#400
  def method_missing(command, *args, **_arg2, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def mget(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def monitor(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def move(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def mset(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def msetnx(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#309
  def multi(&block); end

  # source://redis-namespace//lib/redis/namespace.rb#321
  def namespace(desired_namespace = T.unsafe(nil)); end

  # Sets the attribute namespace
  #
  # @param value the value to set the attribute namespace to.
  #
  # source://redis-namespace//lib/redis/namespace.rb#256
  def namespace=(_arg0); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def object(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def persist(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def pexpire(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def pexpireat(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def pexpiretime(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def pfadd(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def pfcount(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def pfmerge(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def ping(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#317
  def pipelined(&block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def psetex(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def psubscribe(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def pttl(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def publish(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def punsubscribe(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#374
  def quit(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#374
  def randomkey(*args, **_arg1, &block); end

  # Returns the value of attribute redis.
  #
  # source://redis-namespace//lib/redis/namespace.rb#257
  def redis; end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def rename(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def renamenx(*args, **_arg1, &block); end

  # emulate Ruby 1.9+ and keep respond_to_missing? logic together.
  #
  # @return [Boolean]
  #
  # source://redis-namespace//lib/redis/namespace.rb#299
  def respond_to?(command, include_private = T.unsafe(nil)); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def restore(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def rpop(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def rpoplpush(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def rpush(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def rpushx(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def sadd(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def sadd?(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#374
  def save(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def scan(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def scan_each(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def scard(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#374
  def script(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def sdiff(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def sdiffstore(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#374
  def select(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#296
  def self_respond_to?(*_arg0); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def set(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def setbit(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def setex(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def setnx(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def setrange(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#374
  def shutdown(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def sinter(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def sinterstore(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def sismember(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#374
  def slaveof(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def smembers(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def smismember(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def smove(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def sort(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def spop(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def srandmember(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def srem(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def srem?(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def sscan(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def sscan_each(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def strlen(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def subscribe(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def sunion(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def sunionstore(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def time(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def ttl(*args, **_arg1, &block); end

  # Ruby defines a now deprecated type method so we need to override it here
  # since it will never hit method_missing
  #
  # source://redis-namespace//lib/redis/namespace.rb#292
  def type(key); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def unlink(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def unsubscribe(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def unwatch(*args, **_arg1, &block); end

  # Returns the value of attribute warning.
  #
  # source://redis-namespace//lib/redis/namespace.rb#258
  def warning; end

  # Sets the attribute warning
  #
  # @param value the value to set the attribute warning to.
  #
  # source://redis-namespace//lib/redis/namespace.rb#258
  def warning=(_arg0); end

  # @return [Boolean]
  #
  # source://redis-namespace//lib/redis/namespace.rb#276
  def warning?; end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def watch(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def zadd(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def zcard(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def zcount(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def zincrby(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def zinterstore(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def zpopmax(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def zpopmin(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def zrange(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def zrangebylex(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def zrangebyscore(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def zrank(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def zrem(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def zremrangebylex(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def zremrangebyrank(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def zremrangebyscore(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def zrevrange(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def zrevrangebylex(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def zrevrangebyscore(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def zrevrank(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def zscan(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def zscan_each(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def zscore(*args, **_arg1, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#394
  def zunionstore(*args, **_arg1, &block); end

  protected

  # source://redis-namespace//lib/redis/namespace.rb#542
  def redis=(redis); end

  private

  # source://redis-namespace//lib/redis/namespace.rb#592
  def add_namespace(key); end

  # source://redis-namespace//lib/redis/namespace.rb#579
  def call_site; end

  # Avoid modifying the caller's (pass-by-reference) arguments.
  #
  # source://redis-namespace//lib/redis/namespace.rb#569
  def clone_args(arg); end

  # source://redis-namespace//lib/redis/namespace.rb#623
  def create_enumerator(&block); end

  # source://redis-namespace//lib/redis/namespace.rb#583
  def namespaced_block(command, &block); end

  # source://redis-namespace//lib/redis/namespace.rb#606
  def rem_namespace(key); end

  # @return [Boolean]
  #
  # source://redis-namespace//lib/redis/namespace.rb#428
  def respond_to_missing?(command, include_all = T.unsafe(nil)); end

  # source://redis-namespace//lib/redis/namespace.rb#549
  def ruby2_keywords_hash(kwargs); end

  # @return [Boolean]
  #
  # source://redis-namespace//lib/redis/namespace.rb#635
  def supports_scan?; end

  # source://redis-namespace//lib/redis/namespace.rb#558
  def wrapped_send(redis_client, command, args = T.unsafe(nil), &block); end

  class << self
    # Returns the value of attribute sadd_returns_boolean.
    #
    # source://redis-namespace//lib/redis/namespace.rb#253
    def sadd_returns_boolean; end

    # Sets the attribute sadd_returns_boolean
    #
    # @param value the value to set the attribute sadd_returns_boolean to.
    #
    # source://redis-namespace//lib/redis/namespace.rb#253
    def sadd_returns_boolean=(_arg0); end

    # Returns the value of attribute srem_returns_boolean.
    #
    # source://redis-namespace//lib/redis/namespace.rb#253
    def srem_returns_boolean; end

    # Sets the attribute srem_returns_boolean
    #
    # @param value the value to set the attribute srem_returns_boolean to.
    #
    # source://redis-namespace//lib/redis/namespace.rb#253
    def srem_returns_boolean=(_arg0); end
  end
end

# source://redis-namespace//lib/redis/namespace.rb#214
Redis::Namespace::ADMINISTRATIVE_COMMANDS = T.let(T.unsafe(nil), Hash)

# source://redis-namespace//lib/redis/namespace.rb#236
Redis::Namespace::COMMANDS = T.let(T.unsafe(nil), Hash)

# source://redis-namespace//lib/redis/namespace.rb#232
Redis::Namespace::DEPRECATED_COMMANDS = T.let(T.unsafe(nil), Hash)

# source://redis-namespace//lib/redis/namespace.rb#206
Redis::Namespace::HELPER_COMMANDS = T.let(T.unsafe(nil), Hash)

# The following tables define how input parameters and result
# values should be modified for the namespace.
#
# COMMANDS is a hash. Each key is the name of a command and each
# value is a two element array.
#
# The first element in the value array describes how to modify the
# arguments passed. It can be one of:
#
#   nil
#     Do nothing.
#   :first
#     Add the namespace to the first argument passed, e.g.
#       GET key => GET namespace:key
#   :all
#     Add the namespace to all arguments passed, e.g.
#       MGET key1 key2 => MGET namespace:key1 namespace:key2
#   :exclude_first
#     Add the namespace to all arguments but the first, e.g.
#   :exclude_last
#     Add the namespace to all arguments but the last, e.g.
#       BLPOP key1 key2 timeout =>
#       BLPOP namespace:key1 namespace:key2 timeout
#   :exclude_options
#     Add the namespace to all arguments, except the last argument,
#     if the last argument is a hash of options.
#       ZUNIONSTORE key1 2 key2 key3 WEIGHTS 2 1 =>
#       ZUNIONSTORE namespace:key1 2 namespace:key2 namespace:key3 WEIGHTS 2 1
#   :alternate
#     Add the namespace to every other argument, e.g.
#       MSET key1 value1 key2 value2 =>
#       MSET namespace:key1 value1 namespace:key2 value2
#   :sort
#     Add namespace to first argument if it is non-nil
#     Add namespace to second arg's :by and :store if second arg is a Hash
#     Add namespace to each element in second arg's :get if second arg is
#       a Hash; forces second arg's :get to be an Array if present.
#   :eval_style
#     Add namespace to each element in keys argument (via options hash or multi-args)
#   :scan_style
#     Add namespace to :match option, or supplies "#{namespace}:*" if not present.
#
# The second element in the value array describes how to modify
# the return value of the Redis call. It can be one of:
#
#   nil
#     Do nothing.
#   :all
#     Add the namespace to all elements returned, e.g.
#       key1 key2 => namespace:key1 namespace:key2
#
# source://redis-namespace//lib/redis/namespace.rb#56
Redis::Namespace::NAMESPACED_COMMANDS = T.let(T.unsafe(nil), Hash)

# source://redis-namespace//lib/redis/namespace.rb#199
Redis::Namespace::TRANSACTION_COMMANDS = T.let(T.unsafe(nil), Hash)

# source://redis-namespace//lib/redis/namespace/version.rb#5
Redis::Namespace::VERSION = T.let(T.unsafe(nil), String)
