# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `ruby-lsp-rails` gem.
# Please instead update this file by running `bin/tapioca gem ruby-lsp-rails`.

# source://ruby-lsp-rails//lib/ruby_lsp_rails/version.rb#4
module RubyLsp; end

# # Supported features
#
# - [Hover](rdoc-ref:RubyLsp::Rails::Hover)
# - [CodeLens](rdoc-ref:RubyLsp::Rails::CodeLens)
#
# source://ruby-lsp-rails//lib/ruby_lsp_rails/version.rb#5
module RubyLsp::Rails; end

# source://ruby-lsp-rails//lib/ruby_lsp_rails/rack_app.rb#6
class RubyLsp::Rails::RackApp
  # source://ruby-lsp-rails//lib/ruby_lsp_rails/rack_app.rb#12
  sig { params(env: T::Hash[T.untyped, T.untyped]).returns(T::Array[T.untyped]) }
  def call(env); end

  private

  # source://ruby-lsp-rails//lib/ruby_lsp_rails/rack_app.rb#53
  sig { returns(T::Array[T.untyped]) }
  def not_found; end

  # source://ruby-lsp-rails//lib/ruby_lsp_rails/rack_app.rb#31
  sig { params(model_name: ::String).returns(T::Array[T.untyped]) }
  def resolve_database_info_from_model(model_name); end
end

# source://ruby-lsp-rails//lib/ruby_lsp_rails/rack_app.rb#9
RubyLsp::Rails::RackApp::BASE_PATH = T.let(T.unsafe(nil), String)

# source://ruby-lsp-rails//lib/ruby_lsp_rails/railtie.rb#9
class RubyLsp::Rails::Railtie < ::Rails::Railtie; end

# source://ruby-lsp-rails//lib/ruby_lsp_rails/version.rb#6
RubyLsp::Rails::VERSION = T.let(T.unsafe(nil), String)
