---
version: "2"
plugins:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  fixme:
    enabled: true
  stylelint:
    enabled: true
checks:
  return-statements:
    config:
      threshold: 5
exclude_patterns:
- config/
- db/
- doc/
- script/
- spec/
