---
version: "2"
plugins:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  fixme:
    enabled: true
checks:
  method-complexity:
    config:
      threshold: 8
  return-statements:
    config:
      threshold: 5
exclude_patterns:
- config/
- db/
- doc/
- script/
- spec/
- .github/
- .**
- app/assets/images/
- backstop/then/
- bin/
- bin-docker/
- public/
