extends:
  - eslint:recommended

root: true

parserOptions:
  ecmaVersion: 6

env:
  browser: true
  jquery: true

# http://eslint.org/docs/rules/
rules:
  # Possible Errors
  no-console: 0
  no-extra-parens: 0
  no-negated-in-lhs: 2
  valid-jsdoc: 0

  # Best Practices
  accessor-pairs: 2
  block-scoped-var: 2
  complexity: [2, 6]
  consistent-return: 1
  curly: 0
  default-case: 0
  dot-location: [2, property]
  dot-notation: 1
  eqeqeq: 2
  guard-for-in: 2
  no-alert: 0
  no-caller: 1
  no-div-regex: 2
  no-else-return: 2
  no-empty-function: 2
  no-eq-null: 2
  no-eval: 2
  no-extend-native: 2
  no-extra-bind: 2
  no-extra-label: 2
  no-floating-decimal: 2
  no-implicit-coercion: 2
  no-implicit-globals: 0
  no-implied-eval: 2
  no-invalid-this: 2
  no-iterator: 2
  no-labels: 2
  no-lone-blocks: 2
  no-loop-func: 2
  no-magic-numbers: 0
  no-multi-spaces: 2
  no-multi-str: 2
  no-new: 2
  no-new-func: 2
  no-new-wrappers: 2
  no-octal-escape: 2
  no-param-reassign: 0
  no-proto: 2
  no-restricted-properties: 2
  no-return-assign: 2
  no-return-await: 2
  no-script-url: 2
  no-self-compare: 2
  no-sequences: 2
  no-throw-literal: 2
  no-unmodified-loop-condition: 2
  no-unused-expressions: 2
  no-useless-call: 2
  no-useless-concat: 2
  no-useless-return: 2
  no-void: 2
  no-warning-comments: 1
  prefer-promise-reject-errors: 2
  radix: 0
  require-await: 1
  vars-on-top: 0
  wrap-iife: 2
  yoda: 1

  # Strict
  strict: 0

  # Variables
  init-declarations: 0
  no-catch-shadow: 2
  no-label-var: 2
  no-restricted-globals: 2
  no-shadow: 2
  no-undef-init: 2
  no-undefined: 2
  no-unused-vars:
    - 2
    - varsIgnorePattern: ^_.*$
      argsIgnorePattern: ^_.*$
  no-use-before-define:
    - 2
    - functions: false

  # Node.js and CommonJS
  callback-return: 2
  global-require: 2
  handle-callback-err: 2
  no-mixed-requires: 1
  no-new-require: 1
  no-path-concat: 2
  no-process-env: 1
  no-process-exit: 2
  no-restricted-modules: 2
  no-sync: 1

  # Stylistic Issues
  array-bracket-spacing: 1
  block-spacing: 1
  brace-style:
    - 1
    - 1tbs
    - allowSingleLine: true
  camelcase:
    - 1
    - properties: never
  capitalized-comments: 0
  comma-dangle: 0
  comma-spacing: 1
  comma-style: 1
  computed-property-spacing: 1
  consistent-this: 0
  eol-last: 1
  func-call-spacing: 1
  func-name-matching: 0
  func-names: 0
  func-style: 0
  id-blacklist: 0
  id-length: 0
  id-match: 0
  indent: [2, 2]
  jsx-quotes: [1, prefer-single]
  key-spacing: 1
  keyword-spacing: 2
  line-comment-position: 0
  linebreak-style: 1
  lines-around-comment: 0
  lines-around-directive: 0
  max-depth: 0
  max-len: 0
  max-lines: 0
  max-nested-callbacks: 0
  max-params: 0
  max-statements: [1, 30]
  max-statements-per-line: 0
  multiline-ternary: 0
  new-cap: 0
  new-parens: 1
  newline-after-var: 0
  newline-before-return: 0
  newline-per-chained-call: 0
  no-array-constructor: 1
  no-bitwise: 1
  no-continue: 0
  no-inline-comments: 0
  no-lonely-if: 1
  no-mixed-operators: 2
  no-multi-assign: 1
  no-multiple-empty-lines: 0
  no-negated-condition: 1
  no-nested-ternary: 1
  no-new-object: 2
  no-plusplus:
    - 2
    - allowForLoopAfterthoughts: true
  no-restricted-syntax: 0
  no-tabs: 0
  no-ternary: 0
  no-trailing-spaces: 2
  no-underscore-dangle: 0
  no-unneeded-ternary: 2
  no-whitespace-before-property: 2
  nonblock-statement-body-position: 0
  object-curly-newline: 0
  object-curly-spacing: 0
  object-property-newline: 0
  one-var: 0
  one-var-declaration-per-line: 0
  operator-assignment: 1
  operator-linebreak: 0
  padded-blocks: 0
  quote-props: 0
  quotes: 0
  require-jsdoc: 0
  semi: 2
  semi-spacing: 2
  sort-keys: 0
  sort-vars: 0
  space-before-blocks: 2
  space-before-function-paren:
    - 2
    - anonymous: never
      named: never
      asyncArrow: always
  space-in-parens: 1
  space-infix-ops: 0
  space-unary-ops: 1
  spaced-comment:
    - 2
    - always
    - markers:
      - "= require"
  template-tag-spacing: 0
  unicode-bom: 0
  wrap-regex: 0

  # ECMAScript 6
  arrow-body-style: 0
  arrow-parens: 0
  arrow-spacing: 0
  generator-star-spacing: 0
  no-arrow-condition: 0
  no-const-assign: 2
  no-var: 2
  object-shorthand: 0
  prefer-arrow-callback: 0
  prefer-const: 1
  prefer-reflect: 0
  prefer-spread: 0
  prefer-template: 0
