linters:
  AltText:
    enabled: true

  ClassesBeforeIds:
    enabled: false

  ConsecutiveComments:
    enabled: false

  ConsecutiveSilentScripts:
    enabled: false

  IdNames:
    enabled: false

  InlineStyles:
    exclude: app/views/user_mailer/*

  InstanceVariables:
    enabled: false

  LeadingCommentSpace:
    enabled: false

  LineLength:
    enabled: false

  RuboCop:
    ignored_cops:
      - Lint/BlockAlignment
      - Lint/EndAlignment
      - Lint/Void
      - Layout/ArgumentAlignment
      - Layout/CaseIndentation
      - Layout/ElseAlignment
      - Layout/EndOfLine
      - Layout/HashAlignment
      - Layout/IndentationWidth
      - Layout/LeadingCommentSpace # added
      - Layout/LineLength
      - Layout/ParameterAlignment
      - Layout/TrailingEmptyLines
      - Layout/TrailingWhitespace
      - Metrics/BlockLength
      - Metrics/BlockNesting
      - Naming/FileName
      - Rails/OutputSafety # added
      - Style/FrozenStringLiteralComment
      - Style/IfUnlessModifier
      - Style/Next
      - Style/WhileUntilModifier

  SpaceBeforeScript:
    enabled: false

  SpaceInsideHashAttributes:
    enabled: false

  ViewLength:
    enabled: false
