inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.4
  TargetRailsVersion: 8.0
  # used so rubocop doesn't edit old migrations, doesn't need to be perfectly up to date
  MigratedSchemaVersion: 20241224202900
  DisabledByDefault: false
  SuggestExtensions: false
  UseProjectIndex: true
  Exclude:
    - 'config/initializers/audited.rb'
    - 'config/initializers/will_paginate.rb'
    - 'db/schema.rb'
    - 'backstop/*'
    - 'vendor/**/*'

plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

#################### Gemspec ##############################

Gemspec:
  Enabled: false

#################### Layout ##############################

Layout:
  NewCops: '1.79'

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/CaseIndentation:
  EnforcedStyle: 'end'
  IndentOneStep: true

Layout/CommentIndentation:
  Exclude: ['spec/spec_helper.rb']

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: 'variable'

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/FirstArrayElementIndentation:
  EnforcedStyle: 'consistent'

Layout/FirstHashElementIndentation:
  EnforcedStyle: 'consistent'

Layout/HashAlignment:
  EnforcedHashRocketStyle: table

Layout/HeredocIndentation:
  Enabled: true
  Exclude:
    - 'db/migrate/**/*'

Layout/IndentationWidth:
  Enabled: true
  Width: 2

Layout/LineLength:
  Enabled: true
  Max: 150
  Exclude:
    - 'app/controllers/api/**/*'
    - 'db/seeds/post.rb'
    - 'db/seeds/reply.rb'

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: symmetrical
  Exclude:
    - 'spec/**/*'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: 'indented'

Layout/MultilineMethodParameterLineBreaks:
  AllowMultilineFinalElement: true

Layout/MultilineOperationIndentation:
  EnforcedStyle: aligned
  Exclude:
    - 'app/helpers/writable_helper.rb'

Layout/ParameterAlignment:
  EnforcedStyle: 'with_fixed_indentation'

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: 'no_space'

#################### Lint ################################

Lint:
  NewCops: '1.90'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'spec/lib/presentable_spec.rb'

Lint/DeprecatedReference:
  Enabled: false # we don't use @deprecated

Lint/IncompatibleIoSelectWithFiberScheduler:
  Enabled: false # unlikely to use IO select

Lint/MissingSuper:
  Exclude:
    - 'app/services/daily_report.rb'

Lint/ParenthesesAsGroupedExpression:
  Exclude:
    - 'spec/**/*'

Lint/SuppressedException:
  Exclude:
    - 'spec/jobs/application_job_spec.rb'
    - 'spec/jobs/generate_flat_post_job_spec.rb'

###################### Metrics ####################################

Metrics:
  NewCops: '1.47'

Metrics/AbcSize:
  Enabled: false
  Max: 20

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: true
  Max: 4

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

####################### Naming ################################

Naming:
  NewCops: '1.76'

Naming/AccessorMethodName:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames:
    - js
    - id

Naming/PredicateMethod:
  Enabled: false

Naming/PredicatePrefix:
  Enabled: false

Naming/VariableNumber:
  Exclude:
    - 'spec/**/*'

####################### Performance ################################

Performance:
  NewCops: '1.24'

Performance/CollectionLiteralInLoop:
  Enabled: false

Performance/ConcurrentMonotonicTime:
  Enabled: false # we don't use monotonic time

Performance/StringBytesize:
  Enabled: false
  # we don't use byte operations

##################### Rails ##################################

Rails:
  Enabled: true
  NewCops: '2.34'

Rails/ActionControllerTestCase:
  Enabled: false
  # we don't use rails native tests, and also, no.

Rails/ActionOrder:
  ExpectedOrder:
    - index
    - new
    - create
    - show
    - edit
    - update
    - destroy

Rails/AddColumnIndex:
  Enabled: false
  # disabled because we don't run cops on db/*, otherwise good

Rails/ApplicationController:
  Exclude:
    - 'app/controllers/api/api_controller.rb'

Rails/Blank:
  UnlessPresent: false

Rails/DotSeparatedKeys:
  Enabled: false # I18n

Rails/Env:
  Enabled: false
  # we don't use feature flags (yet?)

Rails/FilePath:
  EnforcedStyle: 'arguments'

Rails/HasManyOrHasOneDependent:
  Exclude:
    - 'app/models/user.rb'

Rails/HelperInstanceVariable:
  Enabled: false

Rails/I18nLazyLookup:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Rails/I18nLocaleAssignment:
  Enabled: false

Rails/Output:
  Exclude:
    - 'app/services/reply_scraper.rb' # post_scraper.rb (which calls ReplyScraper) is run manually in the command line
    - 'db/seeds.rb'
    - 'db/seeds/**' # seed files are run from the command line

Rails/PluckInWhere:
  Enabled: false

Rails/ReadWriteAttribute:
  Enabled: false
  # read_attribute(:attr) and self[:attr] are no longer equivalent

Rails/RedundantTravelBack:
  Enabled: false
  # we don't use rails tests

Rails/SaveBang:
  Enabled: true

Rails/ShortI18n:
  Enabled: false

Rails/StrongParametersExpect:
  Enabled: false # we do a lot of custom logic around parameter existance

Rails/ThreeStateBooleanColumn:
  Enabled: false # we don't run cops on db/; otherwise good

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/WhereExists:
  Enabled: false

Rails/WhereNot:
  Enabled: true

Rails/WhereRange:
  Enabled: false
  # we don't use this format

################## RSpec #################################

RSpec:
  NewCops: '3.10'

RSpec/BeEq:
  Enabled: false

RSpec/ContainExactly:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/Dialect:
  PreferredMethods:
    background: :before
    given:      :let
    given!:     :let!

RSpec/DescribedClass:
  EnforcedStyle: explicit

RSpec/DescribeMethod:
  Exclude:
    - 'spec/controllers/posts/*'
    - 'spec/controllers/replies/*'
    - 'spec/controllers/bookmarks/*'

RSpec/EmptyOutput:
  Enabled: false # we don't use the output matcher

RSpec/ExampleLength:
  Enabled: false

RSpec/ExampleWording:
  Enabled: false

RSpec/ExpectChange:
  EnforcedStyle: block

RSpec/HookArgument:
  EnforcedStyle: each

RSpec/IndexedLet:
  Enabled: false

RSpec/IsExpectedSpecify:
  Enabled: false # we don't use specify and is_expected

RSpec/LeakyConstantDeclaration:
  Exclude:
    - 'spec/lib/presentable_spec.rb'

RSpec/MatchArray:
  Enabled: false

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/PendingWithoutReason:
  Enabled: false

RSpec/RepeatedSubjectCall:
  Enabled: false # we don't use subject

RSpec/SpecFilePathFormat:
  Exclude:
    - 'spec/controllers/posts/*'
    - 'spec/controllers/replies/*'
    - 'spec/controllers/bookmarks/*'

RSpec/StubbedMock:
  Exclude:
    - 'spec/script/post_split_spec.rb' # mocking multiple gets in order needs expect

RSpec/SubjectDeclaration:
  Enabled: false # we don't use subject

################## Capybara ####################################

################## Capybara/RSpec ##############################

Capybara/RSpec/HaveSelector:
  Enabled: false

Capybara/RSpec/NegationMatcher:
  EnforcedStyle: have_no

################## FactoryBot ##################################

FactoryBot:
  NewCops: '2.25'

FactoryBot/ExcessiveCreateList:
  MaxAmount: 27 # to allow pagination tests

################## RSpecRails #################################

RSpecRails:
  NewCops: '2.23'

RSpecRails/HaveHttpStatus:
  Enabled: false

RSpecRails/HttpStatus:
  EnforcedStyle: numeric

################## Security ##############################

Security:
  NewCops: '1.28'

################## Style #################################

Style:
  NewCops: '1.90'

Style/AndOr:
  EnforcedStyle: 'conditionals'

Style/ArgumentsForwarding:
  UseAnonymousForwarding: false  # TODO: consider enabling

Style/ArrayFirstLast:
  Enabled: false # unsafe

Style/AsciiComments:
  Enabled: false

Style/AutoResourceCleanup:
  Enabled: true

Style/BitwisePredicate:
  Enabled: false # we don't really use bitwise operations

Style/BlockDelimiters:
  AllowedMethods: ['lambda', 'proc', 'it', 'expect']

Style/CaseLikeIf:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: 'compact'

Style/ClassEqualityComparison:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/ExplicitBlockArgument:
  Enabled: false

Style/ExponentialNotation:
  Enabled: false
  # we don't use exponents

Style/FileNull:
  Enabled: false
  # we don't use /dev/null

Style/FileTouch:
  Enabled: false
  # we don't use file operations

Style/FileWrite:
  Enabled: false
  # we don't use file operations

Style/FormatStringToken:
  EnforcedStyle: 'template'

Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'spec/**/*'

Style/GlobalStdStream:
  Enabled: false

Style/GlobalVars:
  AllowedVariables: ['$redis','$safe_ips']

Style/HashAsLastArrayItem:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: either_consistent

Style/InvertibleUnlessCondition:
  Enabled: false
  # overriding InverseMethods isn't working right now and we have a lot of fine examples of "unless .present?"
  # TODO: review this

Style/KeywordParametersOrder:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/MapIntoArray:
  Enabled: false
  # unsafe, and we don't tend to make this mistake

Style/MixinUsage:
  Exclude: ['bin/*']

Style/MutableConstant:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/OneClassPerFile:
  Exclude:
    - 'app/concerns/presentable.rb'
    - 'app/services/**/*'

Style/OptionalBooleanParameter:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/Proc:
  Enabled: false

Style/QuotedSymbols:
  Enabled: false
  # we don't use quoted symbols OR the cop it's based on

Style/RaiseArgs:
  Enabled: false

Style/RedundantArgument:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/RedundantException:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: 'slashes'
  AllowInnerSlashes: true

Style/SlicingWithRange:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SuperWithArgsParentheses:
  # unlikely in our code
  Enabled: false

Style/SymbolArray:
  Enabled: false
  EnforcedStyle: 'brackets'

Style/TernaryParentheses:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: 'consistent_comma'

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: 'diff_comma'

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: 'diff_comma'

Style/WordArray:
  Enabled: false

Style/YAMLFileRead:
  Enabled: true
