AllCops:
  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.1
  DisabledByDefault: false
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'db/migrate/*'
    - 'db/seeds.rb'
    - 'spec/spec_helper.rb'
    - 'wraith/*'

Rails:
  Enabled: true

#################### Layout ##############################

Layout/AlignArguments:
  EnforcedStyle: with_fixed_indentation

Layout/AlignHash:
  Enabled: false

Layout/AlignParameters:
  Enabled: false

Layout/CaseIndentation:
  Enabled: true
  EnforcedStyle: 'end'
  IndentOneStep: true

Layout/ClosingHeredocIndentation:
  Enabled: true
  Exclude:
    - 'db/migrate/**/*'

Layout/ClosingParenthesisIndentation:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/EmptyLinesAroundAccessModifier:
  Enabled: true

Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: true

Layout/EndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: 'variable'

Layout/EndOfLine:
  Enabled: false

Layout/IndentFirstArgument:
  Enabled: false

Layout/IndentationWidth:
  Enabled: true
  Width: 2

Layout/IndentFirstArrayElement:
  Enabled: true
  EnforcedStyle: 'consistent'

Layout/IndentFirstHashElement:
  Enabled: true
  EnforcedStyle: 'consistent'

Layout/IndentHeredoc:
  Enabled: true
  Exclude:
    - 'db/migrate/**/*'

Layout/MultilineHashBraceLayout:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/MultilineMethodDefinitionBraceLayout:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/SpaceAroundBlockParameters:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Layout/SpaceInLambdaLiteral:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

Layout/SpaceInsideRangeLiteral:
  Enabled: false

Layout/TrailingBlankLines:
  Enabled: false

#################### Lint ################################

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Lint/HandleExceptions:
  Exclude:
    - 'spec/jobs/application_job_spec.rb'
    - 'spec/jobs/generate_flat_post_job_spec.rb'

Lint/ParenthesesAsGroupedExpression:
  Enabled: false

Lint/RescueException:
  Exclude:
    - 'app/jobs/application_job.rb'
    - 'app/jobs/generate_flat_post_job.rb'
    - 'spec/jobs/application_job_spec.rb'
    - 'spec/jobs/generate_flat_post_job_spec.rb'

###################### Metrics ####################################

Metrics/AbcSize:
  Enabled: false
  Max: 20

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: true
  Max: 4

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

####################### Naming ################################

Naming/AccessorMethodName:
  Enabled: false

Naming/AsciiIdentifiers:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - io
    - id
    - to
    - js

##################### Rails ##################################

Rails/Blank:
  Enabled: true
  UnlessPresent: false

Rails/DynamicFindBy:
  Enabled: true
  Whitelist:
    - find_by_sql
    - find_by_id

Rails/HasManyOrHasOneDependent:
  Exclude:
    - 'app/models/user.rb'

Rails/SaveBang:
  Enabled: true

# read_attribute(:attr) and self[:attr] are no longer equivalent
Rails/ReadWriteAttribute:
  Enabled: false

# post_scraper.rb is run manually in the command line so stdout is fine
Rails/Output:
  Exclude:
    - 'app/services/post_scraper.rb'

################## Style #################################

Style/Alias:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/ArrayJoin:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/AutoResourceCleanup:
  Enabled: true

Style/BeginBlock:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/CommandLiteral:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/IfWithSemicolon:
  Enabled: false

Style/InfiniteLoop:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/MultilineMemoization:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/OneLineConditional:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/PercentQLiterals:
  Enabled: false

Style/Proc:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/RedundantException:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringMethods:
  Enabled: true

Style/SymbolArray:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: 'comma'

Style/TrailingCommaInArrayLiteral:
  Enabled: false
  EnforcedStyleForMultiline: 'comma'

Style/TrailingCommaInHashLiteral:
  Enabled: false
  EnforcedStyleForMultiline: 'comma'

Style/TrailingUnderscoreVariable:
  Enabled: true

Style/UnneededCapitalW:
  Enabled: false

Style/VariableInterpolation:
  Enabled: false

Style/WhenThen:
  Enabled: false

Style/WhileUntilModifier:
  Enabled: false

Style/WordArray:
  Enabled: false
