AllCops:
  TargetRubyVersion: 2.6
  TargetRailsVersion: 5.1
  DisabledByDefault: false
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'spec/spec_helper.rb'
    - 'wraith/*'

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

Rails:
  Enabled: true

#################### Layout ##############################

Layout/AlignArguments:
  EnforcedStyle: with_fixed_indentation

Layout/AlignHash:
  EnforcedHashRocketStyle: table

Layout/AlignParameters:
  EnforcedStyle: 'with_fixed_indentation'

Layout/CaseIndentation:
  EnforcedStyle: 'end'
  IndentOneStep: true

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: 'variable'

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/IndentationWidth:
  Enabled: true
  Width: 2

Layout/IndentFirstArrayElement:
  EnforcedStyle: 'consistent'

Layout/IndentFirstHashElement:
  EnforcedStyle: 'consistent'

Layout/IndentHeredoc:
  Enabled: true
  Exclude:
    - 'db/migrate/**/*'

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: 'indented'

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: 'no_space'

Layout/SpaceAroundOperators:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Layout/SpaceInLambdaLiteral:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/SpaceInsideRangeLiteral:
  Enabled: false

#################### Lint ################################

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Lint/HandleExceptions:
  Exclude:
    - 'spec/jobs/application_job_spec.rb'
    - 'spec/jobs/generate_flat_post_job_spec.rb'

Lint/ParenthesesAsGroupedExpression:
  Exclude:
    - 'spec/**/*'

###################### Metrics ####################################

Metrics/AbcSize:
  Enabled: false
  Max: 20

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: true
  Max: 4

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: true
  Max: 150
  Exclude:
    - 'app/controllers/api/**/*'

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

####################### Naming ################################

Naming/AccessorMethodName:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Naming/VariableNumber:
  Exclude:
    - 'spec/**/*'

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - io
    - id
    - to
    - js

##################### Rails ##################################

Rails/Blank:
  Enabled: true
  UnlessPresent: false

Rails/DynamicFindBy:
  Enabled: true
  Whitelist:
    - find_by_sql
    - find_by_id

Rails/HasManyOrHasOneDependent:
  Exclude:
    - 'app/models/user.rb'

Rails/HelperInstanceVariable:
  Enabled: false

Rails/SaveBang:
  Enabled: true

# read_attribute(:attr) and self[:attr] are no longer equivalent
Rails/ReadWriteAttribute:
  Enabled: false

# post_scraper.rb is run manually in the command line so stdout is fine
Rails/Output:
  Exclude:
    - 'app/services/post_scraper.rb'

################## RSpec #################################

Capybara/FeatureMethods:
  EnabledMethods: [feature, scenario]

Rails/HttpStatus:
  EnforcedStyle: numeric

RSpec/AnyInstance:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/DescribedClass:
  EnforcedStyle: explicit

RSpec/ExampleLength:
  Enabled: false

RSpec/ExampleWording:
  Enabled: false

RSpec/ExpectChange:
  EnforcedStyle: block

RSpec/HookArgument:
  EnforcedStyle: each

RSpec/InstanceVariable:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Exclude:
    - 'spec/lib/presentable_spec.rb'

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

################## Style #################################

Style/AndOr:
  EnforcedStyle: 'conditionals'

Style/AsciiComments:
  Enabled: false

Style/AutoResourceCleanup:
  Enabled: true

Style/BlockDelimiters:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: 'compact'

Style/CommentAnnotation:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalVars:
  AllowedVariables: ['$redis']

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/Proc:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/RedundantException:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: 'slashes'
  AllowInnerSlashes: true

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false
  EnforcedStyle: 'brackets'

Style/TernaryParentheses:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: 'comma'

Style/TrailingCommaInArrayLiteral:
  Enabled: false
  EnforcedStyleForMultiline: 'comma'

Style/TrailingCommaInHashLiteral:
  Enabled: false
  EnforcedStyleForMultiline: 'comma'

Style/WordArray:
  Enabled: false
