# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

puts "Seeding database..."

puts "Creating users..."
marri = User.create(username: 'Marri', password: 'nikari', email: "dummy1@example.com", default_editor: 'html', unread_opened: true,
                    role_id: 1, default_view: 'list', layout: 'starrylight', moiety_name: 'Red', moiety: 'AA0000', hide_warnings: true,
                    ignore_unread_daily_report: true, visible_unread: true)
alicorn = User.create(username: 'Alicorn', password: 'alicorn', email: "dummy2@example.com")
kappa = User.create(username: 'Kappa', password: 'pythbox', email: "dummy3@example.com")
aestrix = User.create(username: 'Aestrix', password: 'aestrix', email: "dummy4@example.com")
throne = User.create(username: 'Throne3d', password: 'throne3d', email: "dummy5@example.com", role_id: 2)
teceler = User.create(username: 'Teceler', password: 'teceler', email: "dummy6@example.com", role_id: 2, default_editor: 'html',
                    layout: 'starrydark', ignore_unread_daily_report: true)

puts "Creating avatars..."
Icon.create!([
  { user_id: 1, url: "https://pbs.twimg.com/profile_images/482603626/avatar.png", keyword: "avatar" },
  { user_id: 2, url: "https://33.media.tumblr.com/avatar_ddf517a261d8_64.png", keyword: "avatar" },
  { user_id: 3, url: "http://i.imgur.com/OJSBRcp.jpg", keyword: "avatar" },
  { user_id: 5, url: "https://i.imgur.com/7aXnrK1.jpg", keyword: "avatar" },
  { user_id: 6, url: "https://i.imgur.com/WA1r2Fu.png", keyword: "avatar" }
])
marri.update(avatar_id: 1)
alicorn.update(avatar_id: 2)
kappa.update(avatar_id: 3)
throne.update(avatar_id: 4)
teceler.update(avatar_id: 5)

puts "Creating continuities..."
Board.create!([
  { name: 'Effulgence', creator: alicorn, coauthors: [kappa] },
  { name: 'Incandescence', creator: alicorn, coauthors: [aestrix] },
  { name: 'Pixiethreads', creator: kappa, coauthors: [aestrix] },
  { name: 'Site testing', creator: marri },
  { name: 'Sandboxes', creator: marri, pinned: true },
  { name: 'Witchlight', creator: alicorn, coauthors: [marri] },
])

puts "Creating sections..."
load 'seeds/board_section.rb'

puts "Creating icons..."
load 'seeds/icon.rb'

puts "Creating templates..."
load 'seeds/template.rb'

puts "Creating characters..."
load 'seeds/character.rb'

puts "Creating galleries..."
load 'seeds/gallery.rb'

puts "Creating posts..."
load 'seeds/post.rb'

puts "Creating replies..."
load 'seeds/replies.rb'

Post.all.each { |p| p.update_columns(authors_locked: true) }

puts "Creating tags..."
load 'seeds/tag.rb'
