#!/bin/bash

set -e

if [ "$1" == 'test' ] || [ "$1" == 'reference' ] && [ "$2" != 'logged_out' ]; then
  docker-compose run --rm web bin/rails runner script/before_backstop.rb $2
fi
docker-compose -f docker-compose.yml -f docker-compose-backstop.yml run --rm backstop $1 --config $2
