name: rubocop
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
jobs:
  rubocop:
    name: reviewdog / rubocop
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.8
      - run: gem install activesupport --version 5.2.6
      - name: rubocop
        uses: reviewdog/action-rubocop@v2
        with:
          rubocop_version: gemfile
          rubocop_extensions: rubocop-rails:gemfile rubocop-rspec:gemfile rubocop-performance:gemfile
          reporter: github-pr-review
        if: ${{ github.event_name == 'pull_request' }}
      - name: rubocop
        uses: reviewdog/action-rubocop@v2
        with:
          rubocop_version: gemfile
          rubocop_extensions: rubocop-rails:gemfile rubocop-rspec:gemfile rubocop-performance:gemfile
          filter_mode: nofilter
          reporter: github-check
        if: ${{ github.event_name == 'push' }}
